version: '3.8'

services:
  apache:
    build: .
    container_name: apache-web
    ports:
      - "8080:80"
    networks:
      - my-bridge-network
    depends_on:
      - mysql
    volumes:
      - ./app/:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Ensure this line is correct
    networks:
      - my-bridge-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password  # Use the same root password
    ports:
      - "8081:80"  # Access phpMyAdmin at http://localhost:8081
    networks:
      - my-bridge-network


volumes:
  mysql_data:

networks:
  my-bridge-network:
    driver: bridge

